import { doc, getDoc, runTransaction, serverTimestamp, setDoc } from "firebase/firestore";
import { db } from "../firebase";
export const XP_LEVEL_SIZE = 250;
export const DEFAULT_GAMIFICATION = { xp: 0, coins: 0, level: 1, streak: 0, longestStreak: 0, lastActiveDate: null, achievements: [], rewardedEvents: {} };
export const getLevel = (xp = 0) => Math.max(1, Math.floor(Number(xp || 0) / XP_LEVEL_SIZE) + 1);
export const xpIntoLevel = (xp = 0) => Number(xp || 0) % XP_LEVEL_SIZE;
const dayKey=()=>new Date().toISOString().slice(0,10); const yesterdayKey=()=>{const d=new Date();d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)};
export async function getGamificationProfile(uid){if(!uid)return DEFAULT_GAMIFICATION;const ref=doc(db,"users",uid,"gamification","profile");const snap=await getDoc(ref);return snap.exists()?{...DEFAULT_GAMIFICATION,...snap.data()}:DEFAULT_GAMIFICATION;}
export async function rewardLearningEvent(uid,{eventId,xp=0,coins=0,type="learning",meta={}}){if(!uid||!eventId)return{awarded:false,reason:"missing-event"};const ref=doc(db,"users",uid,"gamification","profile");return runTransaction(db,async tx=>{const snap=await tx.get(ref);const current={...DEFAULT_GAMIFICATION,...(snap.exists()?snap.data():{})};if(current.rewardedEvents?.[eventId])return{awarded:false,reason:"already-awarded",profile:current};const today=dayKey();const streak=current.lastActiveDate===today?current.streak:current.lastActiveDate===yesterdayKey()?Number(current.streak||0)+1:1;const nextXp=Number(current.xp||0)+Number(xp||0);const next={...current,xp:nextXp,coins:Number(current.coins||0)+Number(coins||0),level:getLevel(nextXp),streak,longestStreak:Math.max(Number(current.longestStreak||0),streak),lastActiveDate:today,rewardedEvents:{...(current.rewardedEvents||{}),[eventId]:{type,xp,coins,at:today,meta}},updatedAt:serverTimestamp()};if(!snap.exists())next.createdAt=serverTimestamp();tx.set(ref,next,{merge:true});return{awarded:true,profile:next};});}
export async function unlockAchievement(uid,achievement){if(!uid||!achievement?.id)return false;const ref=doc(db,"users",uid,"gamification","profile");const snap=await getDoc(ref);const current={...DEFAULT_GAMIFICATION,...(snap.exists()?snap.data():{})};if((current.achievements||[]).some(x=>x.id===achievement.id))return false;await setDoc(ref,{...current,achievements:[...(current.achievements||[]),{...achievement,unlockedAt:new Date().toISOString()}],updatedAt:serverTimestamp()},{merge:true});return true;}