import { useCallback, useEffect, useState } from "react";
import { collection, doc, getDocs, serverTimestamp, updateDoc } from "firebase/firestore";
import { CheckCircle2, ChevronDown, ChevronUp, FileQuestion, GraduationCap, Plus, RefreshCw, Save, Trash2 } from "lucide-react";
import { db } from "../firebase";

const emptyQuestion = () => ({ id: `q_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`, question: "", options: ["", "", "", ""], correctIndex: 0, points: 1 });
const emptyContent = () => ({ id: `content_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`, title: "", content: "", url: "" });
const normalizeQuestion = (q, index = 0) => ({ id: q?.id || `q_${Date.now()}_${index}`, question: q?.question || "", options: Array.isArray(q?.options) ? [...q.options, "", "", ""].slice(0, 4) : ["", "", "", ""], correctIndex: Math.min(3, Math.max(0, Number(q?.correctIndex) || 0)), points: Math.max(1, Number(q?.points) || 1) });
const normalizeAssessment = (value) => ({ enabled: value?.enabled !== false, passPercent: Math.min(100, Math.max(1, Number(value?.passPercent) || 70)), questions: Array.isArray(value?.questions) ? value.questions.map(normalizeQuestion) : [] });
const normalizeContent = (value) => Array.isArray(value) ? value.map((item, index) => ({ id: item?.id || `content_${index + 1}`, title: item?.title || item?.name || `Learning material ${index + 1}`, content: item?.content || item?.description || item?.text || "", url: item?.url || "" })) : [];

function QuestionEditor({ question, index, onChange, onRemove, disabled }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">Question {index + 1}</span><button type="button" disabled={disabled} onClick={onRemove} className="rounded-lg p-2 text-red-600 disabled:opacity-40"><Trash2 size={17} /></button></div><textarea value={question.question} disabled={disabled} onChange={(e) => onChange({ question: e.target.value })} rows={2} placeholder="Write the question..." className="mt-4 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none" /><div className="mt-4 grid gap-3 sm:grid-cols-2">{question.options.map((option, i) => <label key={i} className="flex items-center gap-2 rounded-xl border border-slate-200 p-2"><input type="radio" checked={question.correctIndex === i} disabled={disabled} onChange={() => onChange({ correctIndex: i })} /><input value={option} disabled={disabled} onChange={(e) => { const options = [...question.options]; options[i] = e.target.value; onChange({ options }); }} placeholder={`Option ${i + 1}`} className="min-w-0 flex-1 bg-transparent px-1 py-2 text-sm outline-none" /></label>)}</div><div className="mt-3 text-xs text-slate-500">Correct answer is selected by the radio button. Points: <input type="number" min="1" max="20" value={question.points} disabled={disabled} onChange={(e) => onChange({ points: e.target.value })} className="ml-1 w-16 rounded-lg border border-slate-200 px-2 py-1 text-center" /></div></div>; }
function AssessmentEditor({ title, assessment, onChange, disabled }) { const update = (i, patch) => onChange({ questions: assessment.questions.map((q, index) => index === i ? { ...q, ...patch } : q) }); return <section className="rounded-3xl border border-slate-200 bg-slate-50 p-4 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-lg font-extrabold text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-500">Students must pass this assessment before the next required stage unlocks.</p></div><label className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm font-bold"><input type="checkbox" checked={assessment.enabled} disabled={disabled} onChange={(e) => onChange({ enabled: e.target.checked })} /> Enabled</label></div><div className="mt-4 flex items-center gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4"><label className="text-sm font-bold">Pass percentage</label><input type="number" min="1" max="100" value={assessment.passPercent} disabled={disabled} onChange={(e) => onChange({ passPercent: e.target.value })} className="w-24 rounded-xl border border-blue-200 bg-white px-3 py-2 font-bold" /></div><div className="mt-5 space-y-4">{assessment.questions.map((q, i) => <QuestionEditor key={q.id} question={q} index={i} disabled={disabled} onChange={(patch) => update(i, patch)} onRemove={() => onChange({ questions: assessment.questions.filter((_, index) => index !== i) })} />)}</div><button type="button" disabled={disabled} onClick={() => onChange({ questions: [...assessment.questions, emptyQuestion()] })} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Plus size={17} /> Add Question</button></section>; }

export default function AdminAssessments() {
  const [courses, setCourses] = useState([]), [selectedId, setSelectedId] = useState(""), [course, setCourse] = useState(null), [lessonQuizzes, setLessonQuizzes] = useState({}), [courseTest, setCourseTest] = useState(normalizeAssessment()), [finalExam, setFinalExam] = useState(normalizeAssessment()), [learningContent, setLearningContent] = useState([]), [openLessons, setOpenLessons] = useState({}), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState("");
  const loadCourses = useCallback(async () => { setLoading(true); setError(""); try { const snap = await getDocs(collection(db, "courses")); const data = snap.docs.map((item) => ({ id: item.id, ...item.data() })); setCourses(data); if (!selectedId && data[0]) setSelectedId(data[0].id); } catch (err) { setError(err?.message || "Unable to load courses."); } finally { setLoading(false); } }, [selectedId]);
  useEffect(() => { loadCourses(); }, [loadCourses]);
  useEffect(() => { const selected = courses.find((item) => item.id === selectedId) || null; setCourse(selected); if (!selected) return; const stored = selected.assessments || {}; const next = {}; (Array.isArray(selected.lessons) ? selected.lessons : []).forEach((lesson) => { next[lesson.id] = normalizeAssessment(stored.lessonQuizzes?.[lesson.id]); }); setLessonQuizzes(next); setCourseTest(normalizeAssessment(stored.courseTest)); setFinalExam(normalizeAssessment(stored.finalExam)); setLearningContent(normalizeContent(selected.learningContent)); setOpenLessons({}); }, [courses, selectedId]);
  const validateAssessment = (assessment) => { if (!assessment.enabled) return ""; for (const q of assessment.questions) { if (!q.question.trim()) return "Every enabled question needs question text."; if (q.options.some((o) => !String(o).trim())) return "Every question needs all four options."; } return ""; };
  const save = async () => { if (!course || saving) return; for (const group of [courseTest, finalExam, ...Object.values(lessonQuizzes)]) { const problem = validateAssessment(group); if (problem) { setError(problem); return; } } setSaving(true); setError(""); setSuccess(""); try { const assessments = { version: 2, completion: { mode: "learning_sequence", finalExamRequiredWhenEnabled: true }, lessonQuizzes, courseTest, finalExam, updatedAt: serverTimestamp() }; const cleanContent = learningContent.filter((item) => item.title.trim() || item.content.trim() || item.url.trim()).map((item) => ({ ...item, title: item.title.trim(), content: item.content.trim(), url: item.url.trim() })); await updateDoc(doc(db, "courses", course.id), { assessments, learningContent: cleanContent, updatedAt: serverTimestamp() }); setCourses((prev) => prev.map((item) => item.id === course.id ? { ...item, assessments, learningContent: cleanContent } : item)); setSuccess("Learning sequence, content and assessments saved successfully."); } catch (err) { setError(err?.message || "Unable to save assessment settings."); } finally { setSaving(false); } };
  if (loading) return <main className="min-h-[calc(100vh-72px)] bg-slate-50 flex items-center justify-center"><RefreshCw className="animate-spin text-blue-600" size={32} /></main>;
  return <main className="min-h-[calc(100vh-72px)] bg-slate-50"><section className="mx-auto max-w-6xl px-4 py-7 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Assessment Management</p><h1 className="mt-2 text-3xl font-extrabold text-slate-900">Learning Sequence Manager</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Configure lecture quizzes, admin-provided learning material, course test and final exam. Any enabled assessment becomes a required step.</p></div><button type="button" onClick={loadCourses} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"><RefreshCw size={17} /> Refresh</button></div>{error && <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{success && <div className="mt-5 flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700"><CheckCircle2 size={18} /> {success}</div>}<div className="mt-6 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><label className="block text-sm font-bold text-slate-700">Select Course</label><select value={selectedId} onChange={(e) => setSelectedId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold sm:max-w-2xl">{courses.map((item) => <option key={item.id} value={item.id}>{item.title || "Untitled Course"} — {item.duration || "Duration not set"}</option>)}</select></div>{course && <div className="mt-6 space-y-6">
    <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex items-center gap-3"><FileQuestion className="text-blue-600" /><div><h2 className="text-xl font-extrabold text-slate-900">Lecture Quizzes</h2><p className="text-sm text-slate-500">Each lecture can have its own quiz. It unlocks only after verified attendance for that lecture.</p></div></div><div className="mt-5 space-y-3">{(Array.isArray(course.lessons) ? course.lessons : []).map((lesson, index) => { const assessment = lessonQuizzes[lesson.id] || normalizeAssessment(); const open = openLessons[lesson.id]; return <div key={lesson.id} className="overflow-hidden rounded-2xl border border-slate-200"><button type="button" onClick={() => setOpenLessons((p) => ({ ...p, [lesson.id]: !p[lesson.id] }))} className="flex w-full items-center justify-between gap-3 p-4 text-left hover:bg-slate-50"><span><span className="text-xs font-bold uppercase tracking-wide text-blue-600">Lecture {index + 1}</span><span className="mt-1 block font-bold text-slate-900">{lesson.title || `Lesson ${index + 1}`}</span><span className="mt-1 block text-xs text-slate-500">{assessment.questions.length} question(s)</span></span>{open ? <ChevronUp size={19} /> : <ChevronDown size={19} />}</button>{open && <div className="border-t border-slate-200 p-3 sm:p-4"><AssessmentEditor title="Lecture Quiz" assessment={assessment} disabled={saving} onChange={(patch) => setLessonQuizzes((p) => ({ ...p, [lesson.id]: { ...assessment, ...patch } }))} /></div>}</div>; })}</div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-extrabold text-slate-900">Additional Learning Material</h2><p className="mt-1 text-sm text-slate-500">Students see these after all required lecture quizzes are passed. Use for handouts, reading, notes or external resources.</p></div><button type="button" disabled={saving} onClick={() => setLearningContent((prev) => [...prev, emptyContent()])} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Plus size={17} /> Add</button></div><div className="mt-5 space-y-3">{learningContent.map((item, index) => <div key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start gap-3"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">Material {index + 1}</span><button type="button" disabled={saving} onClick={() => setLearningContent((prev) => prev.filter((_, i) => i !== index))} className="ml-auto text-red-600 disabled:opacity-40"><Trash2 size={17} /></button></div><input value={item.title} disabled={saving} onChange={(e) => setLearningContent((prev) => prev.map((x, i) => i === index ? { ...x, title: e.target.value } : x))} placeholder="Title e.g. Handout / Reading" className="mt-3 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" /><textarea value={item.content} disabled={saving} onChange={(e) => setLearningContent((prev) => prev.map((x, i) => i === index ? { ...x, content: e.target.value } : x))} placeholder="Paste notes, reading or instructions..." rows={4} className="mt-3 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" /><input value={item.url} disabled={saving} onChange={(e) => setLearningContent((prev) => prev.map((x, i) => i === index ? { ...x, url: e.target.value } : x))} placeholder="Optional external/handout URL" className="mt-3 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" /></div>)}</div></section>
    <AssessmentEditor title="Course Test" assessment={courseTest} disabled={saving} onChange={(patch) => setCourseTest((prev) => ({ ...prev, ...patch }))} />
    <AssessmentEditor title="Final Exam" assessment={finalExam} disabled={saving} onChange={(patch) => setFinalExam((prev) => ({ ...prev, ...patch }))} />
    <div className="sticky bottom-4 flex justify-end"><button type="button" disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white shadow-xl hover:bg-blue-700 disabled:opacity-50"><Save size={18} /> {saving ? "Saving..." : "Save Learning Sequence"}</button></div>
  </div>}</section></main>;
}
