import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowLeft, Award, CheckCircle2, Clock3, FileCheck2, GraduationCap, Loader2, Lock, Printer, Send, ShieldCheck, XCircle } from "lucide-react";
import { collection, deleteDoc, doc, getDoc, getDocs, query, serverTimestamp, setDoc, where } from "firebase/firestore";
import { onAuthStateChanged } from "firebase/auth";
import { auth, db } from "../firebase";

const ADMIN_UID = "CDwCqUitlaSHEVeWQufCb0lXzMx1";
const certificateId = (uid, courseId) => `OA-${String(courseId || "COURSE").slice(0, 8).toUpperCase()}-${String(uid || "USER").slice(0, 8).toUpperCase()}`;
const requestId = (uid, courseId) => `${uid}_${courseId}`;
const formatDate = (value) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "2-digit", year: "numeric" }).format(value ? new Date(value) : new Date());

function StudentCertificate({ user }) {
  const [params] = useSearchParams();
  const requestedCourseId = params.get("courseId") || "";
  const [courses, setCourses] = useState([]), [selectedId, setSelectedId] = useState(requestedCourseId), [requests, setRequests] = useState({}), [certificates, setCertificates] = useState({}), [loading, setLoading] = useState(true), [submitting, setSubmitting] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  useEffect(() => { let cancelled = false; const load = async () => { setLoading(true); try { const [completionSnap, requestSnap] = await Promise.all([getDocs(query(collection(db, "courseCompletions"), where("userId", "==", user.uid))), getDocs(query(collection(db, "certificateRequests"), where("userId", "==", user.uid)))]); if (cancelled) return; const ids = completionSnap.docs.map((item) => item.data().courseId).filter(Boolean); const courseSnaps = await Promise.all(ids.map((id) => getDoc(doc(db, "courses", id)))); const nextCourses = courseSnaps.filter((s) => s.exists()).map((s) => ({ id: s.id, ...s.data() })).filter((c) => c.certificate !== false); const nextRequests = {}; requestSnap.docs.forEach((item) => { const data = item.data(); if (data.courseId) nextRequests[data.courseId] = { id: item.id, ...data }; }); const certSnaps = await Promise.all(nextCourses.map((c) => getDoc(doc(db, "certificates", certificateId(user.uid, c.id))))); const nextCertificates = {}; certSnaps.forEach((s, i) => { if (s.exists()) nextCertificates[nextCourses[i].id] = { id: s.id, ...s.data() }; }); if (cancelled) return; setCourses(nextCourses); setRequests(nextRequests); setCertificates(nextCertificates); setSelectedId((current) => nextCourses.some((c) => c.id === current) ? current : nextCourses[0]?.id || ""); } catch (err) { if (!cancelled) setError(err?.message || "Unable to load certificate status."); } finally { if (!cancelled) setLoading(false); } }; load(); return () => { cancelled = true; }; }, [user]);
  const selectedCourse = useMemo(() => courses.find((c) => c.id === selectedId) || null, [courses, selectedId]);
  const request = selectedCourse ? requests[selectedCourse.id] : null, certificate = selectedCourse ? certificates[selectedCourse.id] : null;
  const apply = async () => { if (!selectedCourse || submitting || certificate || request?.status === "pending" || request?.status === "approved") return; setSubmitting(true); setError(""); setNotice(""); const id = requestId(user.uid, selectedCourse.id); const payload = { userId: user.uid, courseId: selectedCourse.id, courseTitle: selectedCourse.title || "Untitled Course", studentName: user.displayName || user.email || "Student", status: "pending", requestedAt: serverTimestamp(), updatedAt: serverTimestamp() }; try { if (request?.status === "rejected") await deleteDoc(doc(db, "certificateRequests", id)); await setDoc(doc(db, "certificateRequests", id), payload); setRequests((prev) => ({ ...prev, [selectedCourse.id]: { id, ...payload, status: "pending" } })); setNotice("Certificate application submitted. Admin approval is required before issue."); } catch (err) { setError(err?.message || "Unable to submit the application."); } finally { setSubmitting(false); } };
  if (loading) return <div className="flex min-h-[500px] items-center justify-center"><Loader2 className="animate-spin text-blue-600" size={32} /></div>;
  if (error) return <div className="mx-auto max-w-xl rounded-3xl bg-white p-8 text-center shadow-sm ring-1 ring-slate-200"><ShieldCheck size={40} className="mx-auto text-red-500" /><h1 className="mt-5 text-2xl font-extrabold text-slate-900">Certificate status unavailable</h1><p className="mt-3 text-sm leading-7 text-slate-600">{error}</p></div>;
  if (!selectedCourse) return <div className="mx-auto max-w-3xl rounded-3xl bg-white p-8 text-center shadow-sm ring-1 ring-slate-200 sm:p-14"><Award size={44} className="mx-auto text-slate-400" /><h1 className="mt-6 text-2xl font-extrabold text-slate-900">No Certificate Available Yet</h1><p className="mt-3 text-sm leading-7 text-slate-600">Complete the full learning sequence and required assessments first.</p><Link to="/courses" className="mt-7 inline-flex rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white">Browse Courses</Link></div>;
  if (!certificate) return <div className="mx-auto max-w-4xl">{notice && <div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{notice}</div>}<div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-10"><div className="flex items-start gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><FileCheck2 size={28} /></div><div><p className="text-xs font-black uppercase tracking-widest text-blue-600">Certificate Application</p><h1 className="mt-1 text-2xl font-extrabold text-slate-900">{selectedCourse.title}</h1><p className="mt-3 text-sm leading-7 text-slate-600">Your course completion is verified. Submit an application and the administrator will review it before issuing the certificate.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-emerald-50 p-4"><CheckCircle2 className="text-emerald-600" size={21} /><p className="mt-2 text-xs font-bold text-slate-500">Course</p><p className="font-extrabold text-emerald-700">Completed</p></div><div className="rounded-2xl bg-amber-50 p-4"><Clock3 className="text-amber-600" size={21} /><p className="mt-2 text-xs font-bold text-slate-500">Application</p><p className="font-extrabold text-amber-700">{request?.status === "pending" ? "Pending review" : request?.status === "rejected" ? "Rejected" : "Not submitted"}</p></div><div className="rounded-2xl bg-blue-50 p-4"><ShieldCheck className="text-blue-600" size={21} /><p className="mt-2 text-xs font-bold text-slate-500">Issuance</p><p className="font-extrabold text-blue-700">Admin approval</p></div></div>{request?.adminNote && <div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-700"><strong>Admin note:</strong> {request.adminNote}</div>}<button type="button" onClick={apply} disabled={submitting || request?.status === "pending" || request?.status === "approved"} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{submitting ? "Submitting..." : request?.status === "pending" ? "Application Pending" : <><Send size={17} /> {request?.status === "rejected" ? "Apply Again" : "Apply for Certificate"}</>}</button></div></div>;
  return <div className="mx-auto max-w-5xl"><div className="mb-4 flex justify-end print:hidden"><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white"><Printer size={17} /> Download / Print</button></div><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white p-2 shadow-xl print:rounded-none print:border-0 print:p-0 print:shadow-none"><div className="relative border-4 border-blue-700 p-8 text-center sm:p-14"><div className="certificate-watermark">OA</div><div className="relative"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-blue-50 text-blue-700"><GraduationCap size={34} /></div><p className="mt-4 text-xs font-black tracking-[0.25em] text-blue-700">ONLINE ACADEMY</p><p className="mt-2 text-xs font-bold tracking-widest text-slate-500">OFFICIAL ACADEMIC CERTIFICATE</p><h1 className="mt-3 text-4xl font-black text-slate-900">Certificate of Completion</h1><p className="mt-6 text-sm text-slate-500">This certificate is proudly presented to</p><h2 className="mt-2 text-3xl font-black text-blue-800">{certificate.studentName || user.displayName || user.email}</h2><p className="mt-4 text-sm text-slate-500">for successfully completing</p><h3 className="mt-2 text-2xl font-extrabold text-slate-900">{certificate.courseTitle || selectedCourse.title}</h3><div className="mx-auto mt-7 grid max-w-3xl gap-3 text-left sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">Certificate ID</p><strong className="break-all text-sm">{certificate.certificateId}</strong></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">Issue Date</p><strong className="text-sm">{certificate.issueDate}</strong></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-bold text-emerald-600">Status</p><strong className="flex items-center gap-1 text-sm text-emerald-700"><CheckCircle2 size={15} /> Valid</strong></div></div><div className="mt-7 flex items-end justify-between gap-6 text-left"><div><div className="w-40 border-t border-slate-400 pt-2 text-sm font-bold">Online Academy</div><p className="text-xs text-slate-500">Authorized Issuer</p></div><Award size={48} className="text-blue-700"/><div className="text-right"><div className="ml-auto w-40 border-t border-slate-400 pt-2 text-sm font-bold">Verified Certificate</div><p className="text-xs text-slate-500">Admin Approved</p></div></div></div></div></div></div>;
}

function AdminCertificatePanel() {
  const [requests, setRequests] = useState([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const snap = await getDocs(collection(db, "certificateRequests")); setRequests(snap.docs.map((item) => ({ id: item.id, ...item.data() })).sort((a, b) => (a.status === "pending" ? 0 : 1) - (b.status === "pending" ? 0 : 1))); } catch (err) { setError(err?.message || "Unable to load requests."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const decide = async (request, status) => { if (!request?.id || busy) return; setBusy(request.id); setError(""); setNotice(""); try { await setDoc(doc(db, "certificateRequests", request.id), { status, reviewedAt: serverTimestamp(), updatedAt: serverTimestamp(), adminNote: status === "approved" ? "Certificate approved and issued." : "Certificate application rejected by administrator." }, { merge: true }); if (status === "approved") { const id = certificateId(request.userId, request.courseId); await setDoc(doc(db, "certificates", id), { certificateId: id, userId: request.userId, courseId: request.courseId, studentName: request.studentName || "Student", courseTitle: request.courseTitle || "Untitled Course", issueDate: formatDate(), status: "Valid", issuedBy: "Online Academy", approvedAt: serverTimestamp() }, { merge: true }); } setRequests((prev) => prev.map((item) => item.id === request.id ? { ...item, status } : item)); setNotice(status === "approved" ? "Certificate approved and issued." : "Application rejected."); } catch (err) { setError(err?.message || "Unable to update request."); } finally { setBusy(""); } };
  return <main className="min-h-[calc(100vh-72px)] bg-slate-50 px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-blue-600">Administration</p><h1 className="mt-2 text-3xl font-extrabold text-slate-900">Certificate Requests</h1><p className="mt-2 text-sm text-slate-600">Approve completed-course applications and issue official certificates.</p></div><div className="flex gap-2"><Link to="/admin" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"><ArrowLeft size={17} /> Admin Courses</Link><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"><Clock3 size={17} /> Refresh</button></div></div>{error && <div className="mt-5 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{notice && <div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{notice}</div>}<div className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="flex min-h-60 items-center justify-center"><Loader2 className="animate-spin text-blue-600" /></div> : requests.length === 0 ? <div className="p-10 text-center text-sm font-bold text-slate-500">No certificate applications.</div> : <div className="divide-y divide-slate-100">{requests.map((request) => <div key={request.id} className="p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className={`text-xs font-black uppercase tracking-widest ${request.status === "pending" ? "text-amber-600" : request.status === "approved" ? "text-emerald-600" : "text-red-600"}`}>{request.status || "pending"}</p><h2 className="mt-1 text-lg font-extrabold text-slate-900">{request.courseTitle}</h2><p className="mt-1 text-sm text-slate-600">Student: <strong>{request.studentName}</strong></p><p className="mt-1 font-mono text-xs text-slate-400">{request.userId}</p></div>{request.status === "pending" ? <div className="flex flex-wrap gap-2"><button disabled={busy === request.id} onClick={() => decide(request, "approved")} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><CheckCircle2 size={17} /> Approve & Issue</button><button disabled={busy === request.id} onClick={() => decide(request, "rejected")} className="inline-flex items-center gap-2 rounded-xl bg-red-50 px-4 py-2.5 text-sm font-bold text-red-700 disabled:opacity-50"><XCircle size={17} /> Reject</button></div> : <span className="font-bold text-slate-500">{request.status}</span>}</div></div>)}</div>}</div></div></main>;
}

export default function Certificate() {
  const [user, setUser] = useState(undefined);
  useEffect(() => onAuthStateChanged(auth, (currentUser) => setUser(currentUser || null)), []);
  if (user === undefined) return <main className="flex min-h-[calc(100vh-72px)] items-center justify-center bg-slate-50"><Loader2 className="animate-spin text-blue-600" size={34} /></main>;
  if (!user) return <main className="flex min-h-[calc(100vh-72px)] items-center justify-center bg-slate-50 px-4"><div className="rounded-3xl bg-white p-10 text-center shadow-sm ring-1 ring-slate-200"><Lock size={38} className="mx-auto text-blue-600" /><h1 className="mt-5 text-2xl font-extrabold text-slate-900">Login Required</h1><Link to="/login" className="mt-6 inline-flex rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">Login</Link></div></main>;
  return user.uid === ADMIN_UID ? <AdminCertificatePanel /> : <main className="min-h-[calc(100vh-72px)] bg-slate-50 px-4 py-8 sm:px-6 lg:px-8"><StudentCertificate user={user} /></main>;
}
