import { useEffect, useMemo, useState } from "react";
import { collection, doc, getDoc, onSnapshot, query, where } from "firebase/firestore";
import { onAuthStateChanged } from "firebase/auth";
import { CheckCircle2, ChevronLeft, ChevronRight, FileCheck2, GraduationCap, Lock, RefreshCw, Trophy } from "lucide-react";
import { auth, db } from "../firebase";

const API = "/api/submit-assessment";
const norm = (v) => ({ enabled: v?.enabled !== false, passPercent: Math.min(100, Math.max(1, Number(v?.passPercent) || 70)), questions: Array.isArray(v?.questions) ? v.questions.map((q, i) => ({ id: q?.id || `q_${i + 1}`, question: String(q?.question || ""), options: Array.isArray(q?.options) ? q.options.slice(0, 4) : [], points: Math.max(1, Number(q?.points) || 1) })) : [] });
const has = (v) => v.enabled && v.questions.length > 0;
const key = (t, id) => `${t}:${id}`;
const formatAttemptDate = (value) => { if (!value) return "Date unavailable"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "Date unavailable" : date.toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }); };

function Choice({ q, value, onChange, index }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="font-extrabold leading-6 text-slate-900">{index + 1}. {q.question}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{q.options.map((option, i) => { const selected = Number(value) === i; return <button key={i} type="button" onClick={() => onChange(i)} aria-pressed={selected} className={`flex min-h-12 items-center gap-3 rounded-xl border px-3 py-3 text-left text-sm font-semibold transition ${selected ? "border-blue-500 bg-blue-50 text-blue-800 ring-2 ring-blue-500/10" : "border-slate-200 hover:border-blue-200 hover:bg-slate-50"}`}><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-full border-2 ${selected ? "border-blue-600" : "border-slate-300"}`}>{selected && <span className="h-2.5 w-2.5 rounded-full bg-blue-600" />}</span>{option}</button>; })}</div></div>;
}

export default function CourseAssessments() {
  const courseId = useMemo(() => decodeURIComponent(window.location.pathname.split("/")[2] || ""), []);
  const [user, setUser] = useState(undefined), [course, setCourse] = useState(null), [progress, setProgress] = useState({}), [attempts, setAttempts] = useState({}), [answers, setAnswers] = useState({}), [materialDone, setMaterialDone] = useState({}), [stage, setStage] = useState(0), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [message, setMessage] = useState({ type: "", text: "" });
  useEffect(() => onAuthStateChanged(auth, (u) => setUser(u || null)), []);
  useEffect(() => { if (!user || !courseId) return; setLoading(true); let stopProgress = () => {}, stopAttempts = () => {}; getDoc(doc(db, "courses", courseId)).then((c) => { if (!c.exists()) throw new Error("Course not found."); setCourse({ id: c.id, ...c.data() }); }).catch((e) => setMessage({ type: "error", text: e?.message || "Unable to load course." })); stopProgress = onSnapshot(query(collection(db, "lessonProgress"), where("userId", "==", user.uid), where("courseId", "==", courseId)), (snap) => { const next = {}; snap.docs.forEach((x) => { const d = x.data(); if (d.lessonId) next[d.lessonId] = d; }); setProgress(next); setLoading(false); }, (e) => { setMessage({ type: "error", text: e?.message || "Unable to load lecture progress." }); setLoading(false); }); stopAttempts = onSnapshot(query(collection(db, "assessmentAttempts"), where("userId", "==", user.uid), where("courseId", "==", courseId)), (snap) => { const next = {}; snap.docs.forEach((x) => { const d = x.data(); if (d.type && d.assessmentId) next[key(d.type, d.assessmentId)] = d; }); setAttempts(next); setLoading(false); }, (e) => { setMessage({ type: "error", text: e?.message || "Unable to load assessment progress." }); setLoading(false); }); return () => { stopProgress(); stopAttempts(); }; }, [user, courseId]);
  useEffect(() => { if (!user || !courseId) return; try { setMaterialDone(JSON.parse(localStorage.getItem(`oa_material_${user.uid}_${courseId}`) || "{}")); } catch {} }, [user, courseId]);

  const lessons = useMemo(() => Array.isArray(course?.lessons) ? [...course.lessons].sort((a, b) => (Number(a.order) || 0) - (Number(b.order) || 0)) : [], [course]);
  const watch = Math.max(0, Math.min(100, Number(course?.attendance?.requiredWatchPercent) || 25));
  const quizSteps = useMemo(() => lessons.flatMap((lesson, index) => { const q = norm(course?.assessments?.lessonQuizzes?.[lesson.id]); return has(q) ? [{ kind: "quiz", type: "lesson", id: lesson.id, title: lesson.title || `Lecture ${index + 1}`, index, lesson, q }] : []; }), [lessons, course]);
  const materials = useMemo(() => Array.isArray(course?.learningContent) ? course.learningContent.filter((x) => x?.title || x?.content || x?.url).map((x, i) => ({ kind: "material", id: x.id || `material_${i + 1}`, title: x.title || `Material ${i + 1}`, material: x, done: materialDone[x.id || `material_${i + 1}`] === true })) : [], [course, materialDone]);
  const courseTest = norm(course?.assessments?.courseTest), finalExam = norm(course?.assessments?.finalExam);
  const stages = useMemo(() => [...quizSteps, ...materials, ...(has(courseTest) ? [{ kind: "assessment", type: "course-test", id: "course-test", title: "Course Test", q: courseTest }] : []), ...(has(finalExam) ? [{ kind: "assessment", type: "final", id: "final-exam", title: "Final Exam", q: finalExam }] : [])], [quizSteps, materials, courseTest, finalExam]);
  const passed = (s) => s?.kind === "material" ? s.done : attempts[key(s?.type, s?.id)]?.passed === true;
  const lessonDone = (lesson) => { const p = progress[lesson.id]; return p?.completed === true || Number(p?.percent) >= Number(lesson.requiredWatchPercent || watch); };
  const allQuizzes = quizSteps.every((s) => passed(s));
  const allWatched = lessons.every(lessonDone);
  const courseTestPassed = !has(courseTest) || attempts[key("course-test", "course-test")]?.passed === true;
  const firstIncomplete = stages.findIndex((s) => !passed(s));
  useEffect(() => { if (stages.length) setStage(firstIncomplete >= 0 ? firstIncomplete : stages.length - 1); }, [stages.length, firstIncomplete]);
  const current = stages[stage];
  const history = useMemo(() => stages.filter((s) => s.kind !== "material" && attempts[key(s.type, s.id)]).map((s) => ({ ...s, result: attempts[key(s.type, s.id)] })), [stages, attempts]);

  const lockedReason = (s) => { if (!s) return ""; if (s.kind === "quiz") { if (!lessonDone(s.lesson)) return `Complete at least ${s.lesson?.requiredWatchPercent || watch}% verified active watch time for this lecture first.`; const previous = quizSteps.slice(0, s.index).find((x) => !passed(x)); if (previous) return `Pass ${previous.title} quiz first.`; } if (s.kind === "material" && !allQuizzes) return "Pass every required lecture quiz before opening this material."; if (s.type === "course-test" && !allWatched) return "Complete every lecture before taking the course test."; if (s.type === "course-test" && !allQuizzes) return "Pass every required lecture quiz before taking the course test."; if (s.type === "final" && !courseTestPassed) return "Pass the course test before taking the final exam."; return ""; };
  const lock = lockedReason(current);
  const complete = lessons.every(lessonDone) && quizSteps.every(passed) && materials.every((m) => m.done) && courseTestPassed && (!has(finalExam) || attempts[key("final", "final-exam")]?.passed === true);
  useEffect(() => { if (!complete || !user) return; (async () => { try { const token = await user.getIdToken(); await fetch("/api/complete-course", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ courseId }) }); } catch (e) { console.warn("Completion sync failed", e); } })(); }, [complete, user, courseId]);

  const submit = async () => { if (!current || current.kind === "material" || lock || saving || passed(current)) return; const questions = current.q.questions; if (questions.some((q) => answers[q.id] === undefined)) { setMessage({ type: "error", text: "Please answer every question." }); return; } setSaving(true); setMessage({ type: "", text: "" }); try { const token = await user.getIdToken(); const r = await fetch(API, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ courseId, type: current.type, assessmentId: current.id, answers }) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data?.error || "Assessment submission failed."); setAttempts((p) => ({ ...p, [key(data.type, data.assessmentId)]: data.result })); setAnswers({}); if (data.result.passed) setMessage({ type: "success", text: `Passed — ${data.result.percent}%. This assessment is now locked and cannot be attempted again.` }); else setMessage({ type: "error", text: `Score ${data.result.percent}%. Pass mark is ${data.result.passPercent}%. You may try again.` }); } catch (e) { setMessage({ type: "error", text: e?.message || "Unable to submit assessment." }); } finally { setSaving(false); } };
  const nextMaterial = () => { const next = { ...materialDone, [current.id]: true }; setMaterialDone(next); try { localStorage.setItem(`oa_material_${user.uid}_${courseId}`, JSON.stringify(next)); } catch {} setStage((i) => Math.min(i + 1, stages.length - 1)); setMessage({ type: "", text: "" }); };
  const goNext = () => { setAnswers({}); setMessage({ type: "", text: "" }); setStage((i) => Math.min(i + 1, stages.length - 1)); };

  if (loading || user === undefined) return <div className="mx-auto max-w-4xl px-4 py-10 text-center"><RefreshCw className="mx-auto animate-spin text-blue-600" size={28} /><p className="mt-3 text-sm font-semibold text-slate-500">Loading learning sequence...</p></div>;
  if (!user) return <div className="mx-auto max-w-4xl px-4 py-10 text-center"><GraduationCap className="mx-auto text-blue-600" size={38} /><p className="mt-4 font-bold text-slate-800">Please sign in to continue.</p></div>;
  if (!course) return <div className="mx-auto max-w-4xl px-4 py-10"><div className="rounded-3xl border border-red-200 bg-red-50 p-6 text-center text-sm font-bold text-red-700">{message.text || "Course unavailable."}</div></div>;

  return <section className="mx-auto max-w-4xl px-4 pb-16 pt-6 sm:px-6 lg:px-8"><div className="rounded-3xl border border-blue-100 bg-blue-50 p-4 sm:p-5"><div className="flex items-start gap-3"><GraduationCap className="shrink-0 text-blue-600" /><div><p className="font-black text-slate-900">Learning sequence</p><p className="mt-1 text-sm leading-6 text-slate-600">One step at a time: lecture → quiz → next quiz → learning material → course test → final exam.</p></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-blue-600 transition-all" style={{ width: `${stages.length ? Math.round((stages.filter(passed).length / stages.length) * 100) : 0}%` }} /></div><div className="mt-2 flex justify-between text-xs font-bold text-slate-500"><span>Step {Math.min(stage + 1, Math.max(1, stages.length))} of {Math.max(1, stages.length)}</span><span>{stages.filter(passed).length} completed</span></div></div>
  {message.text && <div className={`mt-4 rounded-2xl border p-4 text-sm font-bold ${message.type === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-red-200 bg-red-50 text-red-700"}`}>{message.text}</div>}
  {!current && <div className="mt-5 rounded-3xl border border-slate-200 bg-white p-8 text-center"><FileCheck2 className="mx-auto text-blue-600" size={36} /><h2 className="mt-4 text-xl font-black text-slate-900">No assessment sequence configured</h2><p className="mt-2 text-sm text-slate-500">Ask the administrator to add quizzes or assessments.</p></div>}
  {current && <div className="mt-5 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-blue-600">{current.kind === "quiz" ? `Lecture ${current.index + 1} Quiz` : current.kind === "material" ? "Learning Material" : current.title}</p><h2 className="mt-1 text-2xl font-black text-slate-900">{current.title}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-black ${lock ? "bg-slate-100 text-slate-500" : passed(current) ? "bg-emerald-100 text-emerald-700" : "bg-blue-100 text-blue-700"}`}>{lock ? "Locked" : passed(current) ? "Passed" : current.kind === "material" ? "Open" : "Ready"}</span></div>
  {lock ? <div className="mt-6 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm font-bold text-amber-800"><Lock className="shrink-0" />{lock}</div> : current.kind === "material" ? <div className="mt-6 rounded-2xl bg-slate-50 p-5"><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{current.material.content || "No text content."}</p>{current.material.url && <a href={current.material.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white">Open material <ChevronRight size={16} /></a>}</div> : passed(current) ? <div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 font-black text-emerald-800"><CheckCircle2 size={20} /> Passed and locked</div><p className="mt-1 text-sm text-emerald-700">You cannot attempt this passed assessment again.</p><div className="mt-4 grid gap-3 sm:grid-cols-4"><div className="rounded-xl bg-white/80 p-3"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">Score</p><p className="mt-1 text-lg font-black text-slate-900">{attempts[key(current.type, current.id)]?.score ?? 0} / {attempts[key(current.type, current.id)]?.total ?? 0}</p></div><div className="rounded-xl bg-white/80 p-3"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">Result</p><p className="mt-1 text-lg font-black text-emerald-700">{attempts[key(current.type, current.id)]?.percent ?? 0}%</p></div><div className="rounded-xl bg-white/80 p-3"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">Pass mark</p><p className="mt-1 text-lg font-black text-slate-900">{attempts[key(current.type, current.id)]?.passPercent ?? current.q.passPercent}%</p></div><div className="rounded-xl bg-white/80 p-3"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">Attempt</p><p className="mt-1 text-lg font-black text-slate-900">#1</p></div></div><p className="mt-3 text-xs font-semibold text-emerald-700">Completed: {formatAttemptDate(attempts[key(current.type, current.id)]?.attemptedAt)}</p></div> : <div className="mt-6 space-y-4">{current.q.questions.map((q, i) => <Choice key={q.id} q={q} index={i} value={answers[q.id]} onChange={(v) => setAnswers((p) => ({ ...p, [q.id]: v }))} />)}</div>}
  <div className="mt-6 flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-between"><button type="button" disabled={stage === 0} onClick={() => { setStage((i) => Math.max(0, i - 1)); setAnswers({}); }} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-black text-slate-700 disabled:opacity-40"><ChevronLeft size={17} /> Previous</button>{lock ? null : current.kind === "material" ? <button type="button" onClick={nextMaterial} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white">Next <ChevronRight size={17} /></button> : passed(current) ? <button type="button" disabled={stage >= stages.length - 1} onClick={goNext} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">Next Quiz <ChevronRight size={17} /></button> : <button type="button" onClick={submit} disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white disabled:opacity-60">{saving ? "Submitting..." : "Submit Assessment"}</button>}</div></div>}
  {history.length > 0 && <div className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><CheckCircle2 className="text-emerald-600" size={22} /><div><h2 className="text-lg font-black text-slate-900">Assessment History</h2><p className="text-sm text-slate-500">Past attempts are view-only. Passed assessments cannot be attempted again.</p></div></div><div className="mt-4 grid gap-3">{history.map((item) => <div key={`${item.type}:${item.id}`} className="flex flex-col gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-blue-600">{item.kind === "quiz" ? `Lecture ${item.index + 1} Quiz` : item.title}</p><p className="mt-1 font-extrabold text-slate-900">{item.title}</p><p className="mt-1 text-xs font-semibold text-slate-500">Completed {formatAttemptDate(item.result?.attemptedAt)}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">{item.result?.passed ? "Passed" : "Attempted"}</span><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-slate-700 ring-1 ring-slate-200">{item.result?.percent ?? 0}%</span><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-slate-700 ring-1 ring-slate-200">{item.result?.score ?? 0}/{item.result?.total ?? 0}</span></div></div>)}</div></div>}
  {complete && <div className="mt-5 rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-start gap-3"><Trophy className="shrink-0 text-emerald-600" size={26} /><div><h2 className="text-xl font-black text-slate-900">Congratulations! Course completed.</h2><p className="mt-1 text-sm text-slate-600">All required stages are complete. Apply for your certificate.</p><a href={`/certificate?courseId=${encodeURIComponent(courseId)}`} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white">Apply for Certificate <FileCheck2 size={17} /></a></div></div></div>}</section>;
}
