import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { onAuthStateChanged } from "firebase/auth";
import { collection, getDocs, limit, orderBy, query, where } from "firebase/firestore";
import {
  ArrowRight, Award, BarChart3, BookOpen, CheckCircle2, ChevronRight, Clock3,
  Code2, Compass, GraduationCap, Menu, PlayCircle, Search, ShieldCheck, Sparkles,
  Star, Target, Users, X, Zap,
} from "lucide-react";
import { auth, db } from "../firebase";
import "./home-animations.css";

const CACHE_KEY = "online_academy_home_courses_v4";
const FEATURED_LIMIT = 8;
const DEFAULT_CATEGORIES = [[Code2, "Programming", "Build real-world skills"], [Compass, "Business", "Grow with confidence"], [Sparkles, "Entertainment", "Learn what you love"], [Target, "Personal Development", "Become your best"]];
const FALLBACK_HERO = { eyebrow: "LEARN WITHOUT LIMITS", title: "Build skills.", highlight: "Shape your future.", description: "Discover structured courses, practical lessons, assessments and certificates — all in one modern learning platform." };

function safeText(value, fallback = "") {
  if (value == null) return fallback;
  if (typeof value === "string") return value.trim() || fallback;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return value.map((item) => safeText(item)).filter(Boolean).join(", ") || fallback;
  if (typeof value === "object") { const candidate = value.url ?? value.label ?? value.name ?? value.title ?? value.text ?? value.value ?? value.displayName; return candidate != null ? safeText(candidate, fallback) : fallback; }
  return fallback;
}
function timestamp(value) { if (!value) return 0; if (typeof value?.toMillis === "function") return value.toMillis(); if (typeof value?.seconds === "number") return value.seconds * 1000; if (typeof value === "number") return value; const parsed = Date.parse(String(value)); return Number.isNaN(parsed) ? 0 : parsed; }
function courseTitle(course) { return safeText(course?.title ?? course?.name, "Untitled Course"); }
function courseCategory(course) { return safeText(course?.category, "Online Course"); }
function courseDescription(course) { return safeText(course?.description, "Start learning with a structured online course."); }
function coursePrice(course) { return Number(course?.price || 0); }
function coursePaid(course) { return course?.isPaid === true || coursePrice(course) > 0; }
function money(value) { return `Rs. ${Number(value || 0).toLocaleString()}`; }

function courseImageSources(course) {
  const values = [course?.imageUrl, course?.imageURL, course?.thumbnailUrl, course?.thumbnailURL, course?.thumbnail, course?.image, course?.courseImage, course?.coverImage, course?.bannerImage, course?.coverUrl, course?.bannerUrl];
  if (Array.isArray(course?.lessons)) course.lessons.forEach((lesson) => values.push(lesson?.thumbnailUrl, lesson?.thumbnailURL, lesson?.thumbnail, lesson?.imageUrl, lesson?.image, lesson?.coverImage));
  return [...new Set(values.map((value) => safeText(value)).filter(Boolean))];
}

function CourseImage({ course, priority = false }) {
  const sources = useMemo(() => courseImageSources(course), [course]);
  const [index, setIndex] = useState(0);
  useEffect(() => setIndex(0), [course?.id]);
  const src = sources[index];
  if (!src) return <div className="oa-image-fallback"><BookOpen size={46} /></div>;
  return <img src={src} alt={courseTitle(course)} loading={priority ? "eager" : "lazy"} decoding="async" fetchPriority={priority ? "high" : "auto"} onError={() => setIndex((current) => current + 1)} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.045]" />;
}

function FeaturedCard({ course, user, index }) {
  const price = coursePrice(course), oldPrice = Number(course?.oldPrice || 0), discount = oldPrice > price && price > 0 ? Math.round(((oldPrice - price) / oldPrice) * 100) : 0, paid = coursePaid(course);
  const rating = Number(course?.rating || course?.averageRating || 4.8), students = Number(course?.studentsCount || course?.enrolledCount || 0), duration = safeText(course?.duration, "Self-paced"), link = user ? `/courses/${course.id}` : "/login";
  return <article className="oa-course-card group flex h-full min-w-0 flex-col overflow-hidden rounded-[1.45rem] border border-slate-200/80 bg-white shadow-[0_10px_35px_rgba(15,23,42,.07)]">
    <div className="relative aspect-[16/9] overflow-hidden bg-slate-950"><CourseImage course={course} priority={index < 2} /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-slate-950/45 via-transparent to-transparent" />{discount > 0 && <span className="absolute left-3 top-3 rounded-full bg-emerald-500 px-3 py-1.5 text-[10px] font-black tracking-wide text-white shadow-lg sm:left-4 sm:top-4">{discount}% OFF</span>}{paid ? <span className="absolute right-3 top-3 rounded-full bg-white px-3 py-1.5 text-xs font-black text-slate-950 shadow-lg sm:right-4 sm:top-4">{money(price)}</span> : <span className="absolute right-3 top-3 rounded-full bg-emerald-500 px-3 py-1.5 text-xs font-black text-white shadow-lg sm:right-4 sm:top-4">FREE</span>}<div className="absolute bottom-3 left-3 flex items-center gap-1.5 rounded-full border border-white/20 bg-slate-950/65 px-2.5 py-1 text-[10px] font-bold text-white backdrop-blur-md"><PlayCircle size={12} /> Learn at your pace</div></div>
    <div className="flex flex-1 flex-col p-4 sm:p-5"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-blue-600"><GraduationCap size={14} />{courseCategory(course)}</div><h3 className="mt-2.5 line-clamp-2 text-[1.08rem] font-black leading-snug tracking-tight text-slate-950 sm:text-xl">{courseTitle(course)}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{courseDescription(course)}</p><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-slate-100 pt-4 text-xs font-semibold text-slate-500"><span className="inline-flex items-center gap-1.5"><Clock3 size={14} />{duration}</span><span className="inline-flex items-center gap-1.5"><Star size={14} className="fill-amber-400 text-amber-400" />{rating.toFixed(1)}</span>{students > 0 && <span className="inline-flex items-center gap-1.5"><Users size={14} />{students.toLocaleString()}</span>}</div><div className="mt-auto grid grid-cols-2 gap-2.5 pt-5"><Link to={link} className="inline-flex min-h-11 items-center justify-center gap-1.5 rounded-xl border border-slate-200 px-3 text-xs font-black text-slate-700 transition hover:border-blue-200 hover:text-blue-700 sm:text-sm">View Course <ArrowRight size={15} /></Link>{paid ? <Link to={user ? `/checkout?courseId=${encodeURIComponent(course.id)}` : "/login"} className="inline-flex min-h-11 items-center justify-center gap-1.5 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 px-3 text-xs font-black text-white shadow-lg shadow-blue-600/20 transition hover:-translate-y-0.5 sm:text-sm">Buy Now <Zap size={15} /></Link> : <span className="inline-flex min-h-11 items-center justify-center rounded-xl bg-emerald-50 px-3 text-xs font-black text-emerald-700 sm:text-sm">Free Course</span>}</div></div>
  </article>;
}

function HomeSkeleton() { return <div className="mx-auto max-w-[1440px] px-5 py-8 sm:px-7 lg:px-10"><div className="oa-skeleton h-[390px] rounded-[2rem] sm:h-[470px]" /><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map((item) => <div key={item} className="oa-skeleton h-28 rounded-2xl" />)}</div></div>; }

export default function Home() {
  const [cached] = useState(() => { try { return JSON.parse(localStorage.getItem(CACHE_KEY) || "null"); } catch { return null; } });
  const [user, setUser] = useState(null), [courses, setCourses] = useState(cached?.courses || []), [loading, setLoading] = useState(!cached?.courses?.length), [search, setSearch] = useState(""), [searchOpen, setSearchOpen] = useState(false), [heroIndex, setHeroIndex] = useState(0), [mobileMenu, setMobileMenu] = useState(false);
  useEffect(() => onAuthStateChanged(auth, setUser), []);

  const loadCourses = useCallback(async () => {
    try {
      const base = collection(db, "courses");
      let snap;
      try { snap = await getDocs(query(base, where("published", "==", true), orderBy("createdAt", "desc"), limit(FEATURED_LIMIT))); }
      catch { snap = await getDocs(query(base, where("published", "==", true), limit(FEATURED_LIMIT))); }
      const next = snap.docs.map((item) => ({ id: item.id, ...item.data() })).filter((item) => item.published === true).sort((a, b) => timestamp(b.createdAt) - timestamp(a.createdAt));
      setCourses(next);
      try { localStorage.setItem(CACHE_KEY, JSON.stringify({ timestamp: Date.now(), courses: next })); } catch {}
    } catch (error) { console.error("Home course loading error:", error); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { loadCourses(); }, [loadCourses]);
  const categories = useMemo(() => { const counts = new Map(); courses.forEach((course) => { const name = courseCategory(course); counts.set(name, (counts.get(name) || 0) + 1); }); return [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 6); }, [courses]);
  const results = useMemo(() => { const term = search.trim().toLowerCase(); if (!term) return []; return courses.filter((course) => [courseTitle(course), courseCategory(course), courseDescription(course), safeText(course?.level)].some((value) => value.toLowerCase().includes(term))).slice(0, 6); }, [courses, search]);
  const heroCourses = useMemo(() => courses.slice(0, 3), [courses]), hero = heroCourses.length ? heroCourses[heroIndex % heroCourses.length] : null;
  useEffect(() => { if (heroCourses.length < 2) return undefined; const timer = window.setInterval(() => setHeroIndex((current) => (current + 1) % heroCourses.length), 6500); return () => window.clearInterval(timer); }, [heroCourses.length]);
  if (loading && !courses.length) return <main className="min-h-screen bg-slate-50"><HomeSkeleton /></main>;

  return <main className="min-h-screen overflow-x-clip bg-[#f7f9fc] text-slate-950">
    <section className="oa-hero relative overflow-hidden text-white"><div className="oa-grid pointer-events-none absolute inset-0" /><div className="oa-orb oa-orb-one" /><div className="oa-orb oa-orb-two" /><div className="relative mx-auto max-w-[1440px] px-5 pb-12 pt-7 sm:px-7 sm:pb-16 sm:pt-10 lg:px-10 lg:pb-20 lg:pt-14 xl:px-12">
      <div className="mb-7 flex items-center justify-between gap-4 lg:hidden"><div className="flex items-center gap-2 font-black"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-500/20 ring-1 ring-white/15"><GraduationCap size={21} /></span>Online Academy</div><button type="button" onClick={() => setMobileMenu((value) => !value)} className="oa-icon-button" aria-label="Toggle menu">{mobileMenu ? <X size={19} /> : <Menu size={19} />}</button></div>
      {mobileMenu && <div className="mb-7 grid gap-2 rounded-2xl border border-white/10 bg-white/[.06] p-2 backdrop-blur-xl lg:hidden"><Link onClick={() => setMobileMenu(false)} to="/courses" className="rounded-xl px-4 py-3 font-bold hover:bg-white/10">Courses</Link><Link onClick={() => setMobileMenu(false)} to="/certificate" className="rounded-xl px-4 py-3 font-bold hover:bg-white/10">Certificate</Link><Link onClick={() => setMobileMenu(false)} to="/verify" className="rounded-xl px-4 py-3 font-bold hover:bg-white/10">Verify</Link></div>}
      <div className="grid items-center gap-12 lg:grid-cols-[1.02fr_.98fr] lg:gap-14 xl:gap-20"><div className="max-w-3xl"><div className="oa-glass-pill inline-flex items-center gap-2 rounded-full px-3.5 py-2 text-[10px] font-black tracking-[.18em] text-blue-100 sm:text-xs"><Sparkles size={14} /> {hero ? courseCategory(hero).toUpperCase() : FALLBACK_HERO.eyebrow}<span className="oa-live-dot h-1.5 w-1.5 rounded-full bg-cyan-300" /></div><h1 className="mt-5 text-[clamp(2.7rem,7vw,5.8rem)] font-black leading-[.96] tracking-[-.05em]">{hero ? courseTitle(hero) : FALLBACK_HERO.title}<span className="mt-2 block bg-gradient-to-r from-blue-200 via-cyan-300 to-indigo-300 bg-clip-text pb-2 text-transparent">{hero ? "Learn at your pace." : FALLBACK_HERO.highlight}</span></h1><p className="mt-6 max-w-2xl text-[15px] leading-7 text-slate-300 sm:text-lg sm:leading-8">{hero ? courseDescription(hero) : FALLBACK_HERO.description}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link to={hero ? `/courses/${hero.id}` : "/courses"} className="oa-button-primary inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl px-6 font-black">Explore Course <ArrowRight size={18} /></Link><Link to={user ? "/dashboard" : "/register"} className="oa-button-secondary inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl px-6 font-black">{user ? "My Dashboard" : "Create Account"}<ArrowRight size={18} /></Link></div><div className="mt-8 grid gap-3 text-xs text-slate-300 sm:grid-cols-3 sm:gap-5 sm:text-sm">{["Structured Learning", "Secure Progress", "Certificate Path"].map((item) => <span key={item} className="inline-flex items-center gap-2"><CheckCircle2 size={14} className="text-cyan-300" />{item}</span>)}</div>{heroCourses.length > 1 && <div className="mt-8 flex items-center gap-2">{heroCourses.map((item, index) => <button key={item.id} type="button" aria-label={`Show ${courseTitle(item)}`} onClick={() => setHeroIndex(index)} className={`oa-slide-dot ${index === heroIndex % heroCourses.length ? "is-active" : ""}`} />)}</div>}</div>
        <div className="oa-dashboard-mockup relative mx-auto w-full max-w-[600px]"><div className="oa-float oa-float-one hidden sm:flex"><ShieldCheck size={14} /> Secure learning</div><div className="rounded-[2rem] border border-white/15 bg-white/[.08] p-2.5 shadow-2xl backdrop-blur-xl sm:p-3"><div className="rounded-[1.55rem] bg-white p-4 text-slate-900 shadow-2xl sm:p-6"><div className="flex items-center justify-between"><div><p className="text-lg font-black">Online Academy</p><p className="text-xs text-slate-400">Smart learning workspace</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black text-emerald-600">READY TO LEARN</span></div><div className="mt-6 overflow-hidden rounded-2xl bg-slate-950"><div className="aspect-[16/7]">{hero ? <CourseImage course={hero} priority /> : <div className="oa-image-fallback"><BookOpen size={48} /></div>}</div></div><div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="flex justify-between text-xs font-black"><span>Learning progress</span><span className="text-blue-600">75%</span></div><div className="mt-2.5 h-2.5 overflow-hidden rounded-full bg-slate-200"><div className="oa-progress-bar h-full w-3/4 rounded-full bg-gradient-to-r from-blue-500 via-indigo-500 to-violet-500" /></div><div className="mt-3 flex justify-between text-[10px] text-slate-400"><span>Keep learning</span><span>Great progress</span></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="oa-mini-card rounded-2xl border border-slate-100 bg-white p-3"><BookOpen size={18} className="text-blue-600" /><p className="mt-2 text-lg font-black">{courses.length}+</p><p className="text-[10px] font-bold text-slate-400">Featured courses</p></div><div className="oa-mini-card rounded-2xl border border-slate-100 bg-white p-3"><Award size={18} className="text-indigo-600" /><p className="mt-2 text-lg font-black">100%</p><p className="text-[10px] font-bold text-slate-400">Self-paced</p></div></div></div></div></div>
      </div>
    </div></section>

    <section className="relative z-10 mx-auto -mt-6 max-w-[1440px] px-5 sm:px-7 lg:px-10 xl:px-12"><div className="oa-stats-card grid overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_18px_55px_rgba(15,23,42,.09)] sm:grid-cols-2 lg:grid-cols-4">{[[BookOpen, courses.length || "—", "Featured Courses"], [Users, "24/7", "Learning Access"], [ShieldCheck, "Secure", "Course Progress"], [Award, "Certificate", "Completion Path"]].map(([Icon, value, label]) => <div key={label} className="flex items-center gap-3 border-b border-slate-100 p-4 last:border-0 sm:p-5 lg:border-b-0 lg:border-r lg:last:border-r-0"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon size={20} /></span><div><p className="text-lg font-black text-slate-950">{value}</p><p className="text-xs font-bold text-slate-400">{label}</p></div></div>)}</div></section>

    <section className="oa-section-content mx-auto max-w-[1440px] px-5 py-12 sm:px-7 sm:py-16 lg:px-10 xl:px-12"><div className="flex items-end justify-between gap-5"><div><p className="oa-kicker">EXPLORE BY INTEREST</p><h2 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Popular categories</h2></div><Link to="/courses" className="hidden items-center gap-1 text-sm font-black text-blue-600 sm:inline-flex">View all <ChevronRight size={17} /></Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(categories.length ? categories : DEFAULT_CATEGORIES).map((item, index) => { const Icon = categories.length ? DEFAULT_CATEGORIES[index % DEFAULT_CATEGORIES.length][0] : item[0]; const name = categories.length ? item[0] : item[1]; const count = categories.length ? item[1] : null; return <Link to={`/courses?category=${encodeURIComponent(name)}`} key={name} className="oa-category-card flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-blue-50 to-indigo-50 text-blue-600"><Icon size={22} /></span><span className="min-w-0"><span className="block truncate font-black text-slate-900">{name}</span><span className="mt-0.5 block text-xs font-semibold text-slate-400">{count ? `${count} course${count > 1 ? "s" : ""}` : item[2]}</span></span><ArrowRight size={16} className="ml-auto shrink-0 text-slate-300" /></Link>; })}</div></section>

    <section className="oa-section-content mx-auto max-w-[1440px] px-5 pb-14 sm:px-7 sm:pb-20 lg:px-10 xl:px-12"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="oa-kicker">HANDPICKED FOR YOU</p><h2 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Featured courses</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Real course thumbnails, clear pricing and fast access — loaded from the published catalogue.</p></div><Link to="/courses" className="inline-flex items-center gap-1 text-sm font-black text-blue-600">View all courses <ChevronRight size={17} /></Link></div><div className="oa-course-grid mt-7">{courses.map((course, index) => <FeaturedCard key={course.id} course={course} user={user} index={index} />)}</div>{!courses.length && <div className="rounded-3xl border border-slate-200 bg-white p-12 text-center"><BookOpen size={40} className="mx-auto text-slate-300" /><h3 className="mt-4 text-xl font-black">Courses are coming soon</h3><p className="mt-2 text-sm text-slate-500">Check back shortly for published courses.</p></div>}</section>

    <section className="oa-section-content border-y border-slate-200 bg-white"><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-7 lg:px-10 xl:px-12"><div className="grid gap-5 lg:grid-cols-3">{[[Users, "Create an account", "Build your learning profile and keep your progress connected across devices."], [BookOpen, "Choose a course", "Explore free and premium courses designed around a clear learning journey."], [PlayCircle, "Learn & complete", "Watch lessons, pass assessments and unlock your completion certificate."]].map(([Icon, title, text], index) => <div key={title} className="oa-step-card rounded-3xl border border-slate-200 bg-slate-50 p-6"><div className="flex items-center justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-blue-600 shadow-sm"><Icon size={23} /></span><span className="text-4xl font-black text-slate-200">0{index + 1}</span></div><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></div></section>

    <section className="oa-section-content mx-auto max-w-[1440px] px-5 py-14 sm:px-7 sm:py-20 lg:px-10 xl:px-12"><div className="oa-cta relative overflow-hidden rounded-[2rem] p-7 text-white sm:p-10 lg:p-14"><div className="oa-cta-grid absolute inset-0" /><div className="relative z-10 flex flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-2xl"><p className="text-xs font-black tracking-[.2em] text-blue-100">START YOUR NEXT CHAPTER</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Ready to learn something new?</h2><p className="mt-3 text-sm leading-7 text-blue-100 sm:text-base">Choose a course today and build skills that move you forward.</p></div><Link to="/courses" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-2xl bg-white px-6 font-black text-blue-700 shadow-xl">Explore Courses <ArrowRight size={18} /></Link></div></div></section>

    <div className="fixed bottom-5 right-5 z-40 hidden sm:block"><button type="button" onClick={() => setSearchOpen(true)} className="oa-search-fab flex h-12 w-12 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-700 shadow-xl" aria-label="Search courses"><Search size={20} /></button></div>
    {searchOpen && <div className="fixed inset-0 z-50 bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) setSearchOpen(false); }}><div className="mx-auto mt-16 max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl"><div className="flex items-center gap-3 border-b border-slate-100 p-4"><Search size={20} className="text-slate-400" /><input autoFocus value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search courses..." className="min-w-0 flex-1 text-base font-semibold outline-none" /><button type="button" onClick={() => setSearchOpen(false)} className="rounded-xl p-2 hover:bg-slate-100" aria-label="Close search"><X size={18} /></button></div><div className="max-h-[65vh] overflow-auto p-3">{results.length ? results.map((course) => <Link key={course.id} to={user ? `/courses/${course.id}` : "/login"} onClick={() => setSearchOpen(false)} className="flex items-center gap-3 rounded-2xl p-3 hover:bg-slate-50"><div className="h-14 w-20 shrink-0 overflow-hidden rounded-xl bg-slate-100"><CourseImage course={course} /></div><div className="min-w-0"><p className="truncate font-black">{courseTitle(course)}</p><p className="text-xs text-slate-500">{courseCategory(course)} · {coursePaid(course) ? money(coursePrice(course)) : "Free"}</p></div><ArrowRight size={17} className="ml-auto text-slate-300" /></Link>) : <div className="p-10 text-center text-sm font-semibold text-slate-400">{search ? "No matching courses found." : "Type to search published courses."}</div>}</div></div></div>}
  </main>;
}
