import { lazy, Suspense, useEffect, useRef, useState } from "react";
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { Award, BadgePercent, BookOpen, ChevronDown, ChevronRight, CreditCard, FileText, Home, LayoutDashboard, LogIn, LogOut, Menu, Megaphone, MoreHorizontal, ShieldCheck, User, UserCog, UserPlus, WalletCards, X } from "lucide-react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { auth } from "./firebase";
import SEO from "./components/SEO";

const HomePage = lazy(() => import("./pages/Home"));
const Courses = lazy(() => import("./pages/Courses"));
const CourseDetails = lazy(() => import("./pages/CourseDetails"));
const CourseAssessments = lazy(() => import("./pages/CourseAssessments"));
const LectureProgressGuard = lazy(() => import("./pages/LectureProgressGuard"));
const PaidCourseGate = lazy(() => import("./components/PaidCourseGate"));
const Login = lazy(() => import("./pages/Login"));
const Register = lazy(() => import("./pages/Register"));
const ForgotPassword = lazy(() => import("./pages/ForgotPassword"));
const ResetPassword = lazy(() => import("./pages/ResetPassword"));
const Dashboard = lazy(() => import("./pages/Dashboard"));
const Profile = lazy(() => import("./pages/Profile"));
const AdminCourses = lazy(() => import("./pages/AdminCourses"));
const AdminAssessments = lazy(() => import("./pages/AdminAssessments"));
const AdminLogin = lazy(() => import("./pages/AdminLogin"));
const TermsPolicy = lazy(() => import("./pages/TermsPolicy"));
const AcademyGuide = lazy(() => import("./pages/AcademyGuide"));
const Certificate = lazy(() => import("./pages/Certificate"));
const VerifyCertificate = lazy(() => import("./pages/VerifyCertificate"));
const VerifyEmail = lazy(() => import("./pages/VerifyEmail"));
const Checkout = lazy(() => import("./pages/Checkout"));
const PaymentResult = lazy(() => import("./pages/PaymentResult"));
const AdminCommerce = lazy(() => import("./pages/AdminCommerce"));
const AdminDiscounts = lazy(() => import("./pages/AdminDiscounts"));
const NotFound = lazy(() => import("./pages/NotFound"));

const ADMIN_EMAIL = "admin@onlineacademy.com";

function Brand({ className = "h-10 w-10" }) { return <img src="/favicon.svg" alt="Online Academy" className={`rounded-xl object-contain ${className}`} />; }
function Avatar({ user, displayName, size = "h-9 w-9" }) { const initials = displayName.split(" ").filter(Boolean).slice(0, 2).map((x) => x[0]).join("").toUpperCase() || "S"; return user?.photoURL ? <img src={user.photoURL} alt="" className={`${size} shrink-0 rounded-xl object-cover ring-1 ring-slate-200`} /> : <span className={`flex ${size} shrink-0 items-center justify-center rounded-xl bg-blue-600 text-xs font-black text-white shadow-sm`}>{initials}</span>; }
function Loader({ text = "Loading..." }) { return <div className="flex min-h-[calc(100vh-76px)] items-center justify-center bg-slate-50"><div className="text-center"><Brand className="mx-auto h-14 w-14" /><div className="mx-auto mt-5 h-8 w-8 animate-spin rounded-full border-4 border-slate-200 border-t-blue-600" /><p className="mt-3 text-sm font-semibold text-slate-500">{text}</p></div></div>; }
function Protected({ user, authReady, children }) { if (!authReady) return <Loader text="Preparing your account..." />; return user ? children : <Navigate to="/login" replace />; }
function AuthOnly({ user, authReady, children }) { if (!authReady) return <Loader />; return user ? <Navigate to="/" replace /> : children; }
function AdminOnly({ user, isAdmin, authReady, children }) { if (!authReady) return <Loader text="Checking admin access..." />; return user && isAdmin ? children : <Navigate to="/admin-login" replace />; }
function CourseRoute() { const { courseId } = useParams(); return <PaidCourseGate courseId={courseId}><LectureProgressGuard><CourseDetails /><CourseAssessments courseId={courseId} /></LectureProgressGuard></PaidCourseGate>; }

function ScrollManager() { const location = useLocation(); useEffect(() => { window.requestAnimationFrame(() => window.scrollTo({ top: 0, left: 0, behavior: "auto" })); }, [location.pathname, location.search, location.hash]); return null; }

function Navbar({ user, isAdmin }) {
  const location = useLocation(); const navigate = useNavigate(); const [mobileOpen, setMobileOpen] = useState(false); const [moreOpen, setMoreOpen] = useState(false);
  useEffect(() => { setMobileOpen(false); setMoreOpen(false); }, [location.pathname, location.search, location.hash]);
  useEffect(() => { document.body.style.overflow = mobileOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [mobileOpen]);
  const active = (to) => { const target = new URL(to, window.location.origin); if (target.pathname === "/") return location.pathname === "/"; if (location.pathname !== target.pathname && !location.pathname.startsWith(`${target.pathname}/`)) return false; return !target.search || location.search === target.search; };
  const logout = async () => { try { await signOut(auth); } catch (error) { console.error("Logout failed", error); } setMoreOpen(false); setMobileOpen(false); navigate("/", { replace: true }); window.scrollTo({ top: 0, left: 0, behavior: "auto" }); };
  const displayName = user?.displayName || user?.email?.split("@")[0] || "Student";
  const mainLinks = [["/", "Home", Home], ["/courses", "Courses", BookOpen], ["/certificate", "Certificate", Award], ["/verify-certificate", "Verify", ShieldCheck]];
  const adminLinks = isAdmin ? [["/admin", "Admin Courses", ShieldCheck], ["/admin/assessments", "Assessments", BookOpen], ["/admin/certificates", "Certificate Requests", Award], ["/admin/commerce", "Paid Courses", CreditCard], ["/admin/commerce?view=finance", "Finance & Billing", WalletCards], ["/admin/commerce?view=users", "User Management", UserCog], ["/admin/commerce?view=promotions", "Offers & Promotions", Megaphone], ["/admin/discounts", "Discounts", BadgePercent]] : [];
  const moreLinks = [...(user ? [["/dashboard", "Dashboard", LayoutDashboard]] : []), ["/about", "About Academy", FileText], ["/help", "Help Center", FileText], ["/terms", "Terms & Policies", FileText], ...(user ? [["/profile", "My Profile", User]] : [["/login", "Login", LogIn], ["/register", "Create Account", UserPlus]]), ...adminLinks];
  const navLinkClass = (to) => `group inline-flex h-10 items-center gap-2 rounded-xl border px-3 text-[13px] font-extrabold transition-all duration-200 ${active(to) ? "border-blue-200 bg-blue-600 text-white shadow-md shadow-blue-600/20" : "border-transparent bg-transparent text-slate-600 hover:border-slate-200 hover:bg-white hover:text-blue-700 hover:shadow-sm"}`;
  const moreButtonClass = `inline-flex h-10 items-center gap-2 rounded-xl border px-3 text-[13px] font-extrabold transition-all duration-200 ${moreOpen || moreLinks.some(([to]) => active(to)) ? "border-blue-200 bg-blue-50 text-blue-700 shadow-sm" : "border-transparent bg-transparent text-slate-600 hover:border-slate-200 hover:bg-white hover:text-blue-700 hover:shadow-sm"}`;
  return <>
    <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 shadow-[0_8px_30px_rgba(15,23,42,0.06)] backdrop-blur-2xl"><div className="mx-auto w-full max-w-[1480px] px-3 sm:px-5 lg:px-8"><nav className="flex min-h-[68px] items-center gap-2 sm:min-h-[74px] sm:gap-3" aria-label="Primary navigation">
      <Link to="/" className="flex min-w-0 flex-1 items-center gap-2.5 sm:gap-3" aria-label="Online Academy home"><Brand className="h-10 w-10 shrink-0 sm:h-11 sm:w-11" /><span className="min-w-0"><span className="block truncate text-[16px] font-black leading-tight tracking-tight text-slate-950 sm:text-lg">Online Academy</span><span className="hidden text-[9px] font-bold tracking-[0.12em] text-slate-400 sm:block">LEARN. GROW. <span className="text-blue-600">SUCCEED.</span></span></span></Link>
      <div className="hidden items-center gap-1 rounded-2xl border border-slate-200 bg-slate-50/90 p-1 lg:flex">{mainLinks.map(([to, label, Icon]) => <Link key={to} to={to} className={navLinkClass(to)}><Icon size={16} />{label}</Link>)}<div className="relative"><button type="button" onClick={() => setMoreOpen((v) => !v)} className={moreButtonClass} aria-expanded={moreOpen}><MoreHorizontal size={16} />More<ChevronDown size={14} className={`transition-transform ${moreOpen ? "rotate-180" : ""}`} /></button>{moreOpen && <><button type="button" className="fixed inset-0 z-[55] cursor-default" aria-label="Close more menu" onClick={() => setMoreOpen(false)} /><div className="absolute right-0 top-[calc(100%+10px)] z-[60] max-h-[min(78vh,720px)] w-80 overflow-y-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl" role="menu"><div className="px-3 pb-2 pt-1 text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">More pages</div>{moreLinks.map(([to, label, Icon]) => <Link key={to} to={to} role="menuitem" className={`flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-bold transition ${active(to) ? "bg-blue-50 text-blue-700" : "text-slate-700 hover:bg-slate-50 hover:text-blue-700"}`}><Icon size={17} />{label}<ChevronRight size={14} className="ml-auto opacity-40" /></Link>)}{user && <button type="button" onClick={logout} className="mt-1 flex min-h-11 w-full items-center gap-3 rounded-xl border-t border-slate-100 px-3 text-left text-sm font-bold text-red-600 hover:bg-red-50"><LogOut size={17} />Logout<ChevronRight size={14} className="ml-auto opacity-40" /></button>}</div></>}</div></div>
      <div className="ml-auto flex shrink-0 items-center gap-2">{user ? <Link to="/dashboard" className="hidden h-11 items-center gap-2 rounded-xl border border-blue-600 bg-blue-600 px-3.5 text-sm font-extrabold text-white shadow-md lg:inline-flex"><LayoutDashboard size={17} />Dashboard</Link> : <Link to="/login" className="hidden h-11 items-center gap-1.5 rounded-xl border border-blue-600 bg-blue-600 px-4 text-sm font-extrabold text-white shadow-md lg:inline-flex">Login <ChevronRight size={16} /></Link>}{user && <Link to="/profile" aria-label="My Profile" title="My Profile" className="hidden h-11 w-11 items-center justify-center rounded-xl border border-slate-200 bg-white p-1.5 shadow-sm xl:flex"><Avatar user={user} displayName={displayName} size="h-8 w-8" /></Link>}<button type="button" onClick={() => setMobileOpen((v) => !v)} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-700 shadow-sm lg:hidden sm:h-11 sm:w-11" aria-label="Toggle navigation">{mobileOpen ? <X size={22} /> : <Menu size={22} />}</button></div>
    </nav></div></header>
    {mobileOpen && <div className="fixed inset-0 z-[70] lg:hidden" role="dialog" aria-modal="true"><button type="button" className="absolute inset-0 h-full w-full bg-slate-950/50" onClick={() => setMobileOpen(false)} aria-label="Close navigation" /><aside className="absolute right-0 top-0 flex h-full w-[min(320px,86vw)] flex-col border-l border-slate-200 bg-white shadow-2xl"><div className="flex min-h-[72px] items-center justify-between border-b px-4"><Link to="/" onClick={() => setMobileOpen(false)} className="flex items-center gap-2.5"><Brand className="h-9 w-9" /><span className="font-black">Online Academy</span></Link><button type="button" onClick={() => setMobileOpen(false)} className="rounded-xl border p-2" aria-label="Close menu"><X size={19} /></button></div><div className="flex-1 overflow-y-auto px-3 py-4"><p className="mb-2 px-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Main navigation</p><div className="space-y-2">{mainLinks.map(([to, label, Icon]) => <Link key={to} to={to} onClick={() => setMobileOpen(false)} className={`flex min-h-11 items-center gap-3 rounded-xl border px-3 text-sm font-extrabold ${active(to) ? "border-blue-200 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-700"}`}><Icon size={18} />{label}<ChevronRight size={15} className="ml-auto opacity-40" /></Link>)}</div><p className="mb-2 mt-6 px-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-400">More pages</p><div className="space-y-2">{moreLinks.map(([to, label, Icon]) => <Link key={to} to={to} onClick={() => setMobileOpen(false)} className={`flex min-h-11 items-center gap-3 rounded-xl border px-3 text-sm font-bold ${active(to) ? "border-blue-200 bg-blue-50 text-blue-700" : "border-slate-100 bg-slate-50/60 text-slate-700"}`}><Icon size={18} />{label}<ChevronRight size={15} className="ml-auto opacity-40" /></Link>)}{user && <button type="button" onClick={logout} className="flex min-h-11 w-full items-center gap-3 rounded-xl border border-red-100 bg-red-50 px-3 text-left text-sm font-bold text-red-600"><LogOut size={18} />Logout<ChevronRight size={15} className="ml-auto opacity-40" /></button>}</div></div>{user && <div className="shrink-0 border-t bg-slate-50 p-3"><Link to="/profile" onClick={() => setMobileOpen(false)} className="flex items-center justify-center rounded-xl border bg-white p-3" aria-label="My Profile"><Avatar user={user} displayName={displayName} size="h-10 w-10" /></Link></div>}</aside></div>}
  </>;
}

function Footer({ user, isAdmin }) {
  const year = new Date().getFullYear(); const logout = async () => { try { await signOut(auth); } catch (error) { console.error("Logout failed", error); } window.location.assign("/"); };
  return <footer className="mt-auto border-t border-slate-200 bg-slate-950 text-slate-300"><div className="mx-auto max-w-[1480px] px-4 py-10 sm:px-6 lg:px-8"><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-3"><Brand className="h-10 w-10" /><span className="font-black text-white">Online Academy</span></div><p className="mt-4 max-w-sm text-sm leading-6 text-slate-400">Structured courses, lessons, assessments, certificates and progress tracking.</p></div><div><p className="mb-4 text-xs font-black uppercase tracking-wider text-white">Explore</p><div className="space-y-2 text-sm"><Link className="block hover:text-white" to="/">Home</Link><Link className="block hover:text-white" to="/courses">Courses</Link><Link className="block hover:text-white" to="/about">About Academy</Link><Link className="block hover:text-white" to="/help">Help Center</Link></div></div><div><p className="mb-4 text-xs font-black uppercase tracking-wider text-white">Learning</p><div className="space-y-2 text-sm"><Link className="block hover:text-white" to="/dashboard">Dashboard</Link><Link className="block hover:text-white" to="/profile">My Profile</Link>{isAdmin && <><Link className="block hover:text-white" to="/admin">Admin Courses</Link><Link className="block hover:text-white" to="/admin/commerce?view=finance">Finance & Billing</Link><Link className="block hover:text-white" to="/admin/commerce?view=users">User Management</Link><Link className="block hover:text-white" to="/admin/commerce?view=promotions">Offers & Promotions</Link></>}</div></div><div><p className="mb-4 text-xs font-black uppercase tracking-wider text-white">Account</p><div className="space-y-2 text-sm">{user ? <button type="button" onClick={logout} className="block text-left hover:text-white">Logout</button> : <><Link className="block hover:text-white" to="/login">Login</Link><Link className="block hover:text-white" to="/register">Create Account</Link></>}</div></div></div><div className="mt-8 border-t border-white/10 pt-5 text-xs text-slate-500">© {year} Online Academy. All rights reserved.</div></div></footer>;
}

export default function App() {
  const [user, setUser] = useState(() => auth.currentUser ?? null); const [authReady, setAuthReady] = useState(() => Boolean(auth.currentUser)); const [isAdmin, setIsAdmin] = useState(() => auth.currentUser?.email?.trim().toLowerCase() === ADMIN_EMAIL); const navigate = useNavigate(); const previousUserRef = useRef(auth.currentUser?.uid ?? null);
  useEffect(() => { let mounted = true; const unsubscribe = onAuthStateChanged(auth, (currentUser) => { if (!mounted) return; const nextUid = currentUser?.uid ?? null; const previousUid = previousUserRef.current; setUser(currentUser); setIsAdmin(currentUser?.email?.trim().toLowerCase() === ADMIN_EMAIL); setAuthReady(true); if (previousUid !== nextUid && (previousUid !== null || nextUid !== null)) { navigate("/", { replace: true }); window.requestAnimationFrame(() => window.scrollTo({ top: 0, left: 0, behavior: "auto" })); } previousUserRef.current = nextUid; }, (error) => { console.error("Firebase auth state error:", error); if (mounted) setAuthReady(true); }); return () => { mounted = false; unsubscribe(); }; }, [navigate]);
  useEffect(() => { const warm = () => { import("./pages/Home").catch(() => {}); import("./pages/Courses").catch(() => {}); }; if ("requestIdleCallback" in window) { const id = window.requestIdleCallback(warm, { timeout: 1800 }); return () => window.cancelIdleCallback?.(id); } const id = window.setTimeout(warm, 900); return () => window.clearTimeout(id); }, []);
  return <div className="flex min-h-screen flex-col bg-slate-50"><SEO /><ScrollManager /><Navbar user={user} isAdmin={isAdmin} /><main className="min-w-0 flex-1"><Suspense fallback={<Loader text="Loading page..." />}><Routes>
    <Route path="/" element={<HomePage user={user} />} /><Route path="/courses" element={<Courses user={user} />} /><Route path="/courses/:courseId" element={<CourseRoute />} /><Route path="/about" element={<AcademyGuide />} /><Route path="/help" element={<AcademyGuide />} /><Route path="/checkout" element={<Protected user={user} authReady={authReady}><Checkout /></Protected>} /><Route path="/payment/success" element={<Protected user={user} authReady={authReady}><PaymentResult /></Protected>} /><Route path="/payment/failed" element={<Protected user={user} authReady={authReady}><PaymentResult failed /></Protected>} /><Route path="/certificate" element={<Certificate />} /><Route path="/verify-certificate" element={<VerifyCertificate />} /><Route path="/verify-email" element={<VerifyEmail />} /><Route path="/terms" element={<TermsPolicy />} /><Route path="/login" element={<AuthOnly user={user} authReady={authReady}><Login /></AuthOnly>} /><Route path="/register" element={<AuthOnly user={user} authReady={authReady}><Register /></AuthOnly>} /><Route path="/forgot-password" element={<AuthOnly user={user} authReady={authReady}><ForgotPassword /></AuthOnly>} /><Route path="/reset-password" element={<ResetPassword />} /><Route path="/admin-login" element={<AdminLogin user={user} isAdmin={isAdmin} adminLoading={!authReady} />} /><Route path="/dashboard" element={<Protected user={user} authReady={authReady}><Dashboard /></Protected>} /><Route path="/profile" element={<Protected user={user} authReady={authReady}><Profile /></Protected>} /><Route path="/admin" element={<AdminOnly user={user} isAdmin={isAdmin} authReady={authReady}><AdminCourses /></AdminOnly>} /><Route path="/admin/assessments" element={<AdminOnly user={user} isAdmin={isAdmin} authReady={authReady}><AdminAssessments /></AdminOnly>} /><Route path="/admin/certificates" element={<AdminOnly user={user} isAdmin={isAdmin} authReady={authReady}><Certificate /></AdminOnly>} /><Route path="/admin/commerce" element={<AdminOnly user={user} isAdmin={isAdmin} authReady={authReady}><AdminCommerce /></AdminOnly>} /><Route path="/admin/discounts" element={<AdminOnly user={user} isAdmin={isAdmin} authReady={authReady}><AdminDiscounts /></AdminOnly>} /><Route path="*" element={<NotFound />} />
  </Routes></Suspense></main><Footer user={user} isAdmin={isAdmin} /></div>;
}
